# Generated by Django 3.2.25 on 2026-04-21 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0015_auto_20260421_1435'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(null=True)),
                ('content', utils.models.RichTextField()),
                ('pdf_file', models.TextField(null=True)),
                ('cover_image', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_plan',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='LessonPlanProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_plan.lessonplan')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
            options={
                'db_table': 'lesson_plan_problem',
                'ordering': ('order',),
                'unique_together': {('lesson_plan', 'problem')},
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='problems',
            field=models.ManyToManyField(related_name='lesson_plans', through='lesson_plan.LessonPlanProblem', to='problem.Problem'),
        ),
    ]
